name: Build and Push

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

      
jobs:
  push:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_OWNER: ${{ vars.REPOSITORY_OWNER }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build Docker Images
        run: docker compose build
      
      - name: Push Docker Images
        run: docker compose push
